# Base configuration for thebox devices

substitutions:
  # Default UI display type, can be overridden by wrapper files
  UI_DISPLAY_TYPE: "SH1106 128x64"

  # default UI-related times
  WARMUP_DURATION_S: '10'
  UPDATE_INTERVAL_NORMAL_MS: '100'
  UPDATE_INTERVAL_BOOT_MS: '100'

esphome:
  name: ${device_name}
  friendly_name: ${device_name}
  min_version: 2025.5.0
  name_add_mac_suffix: false

  project:
    name: thecrbox.thebox2
    version: "1.4.0"

  platformio_options:
    build_flags:
      - "-DUSE_DISPLAY_QR_CODE"
      - "-DWARMUP_DURATION_S=${WARMUP_DURATION_S}"
      - "-DUPDATE_INTERVAL_NORMAL_MS=${UPDATE_INTERVAL_NORMAL_MS}"
      - "-DUPDATE_INTERVAL_BOOT_MS=${UPDATE_INTERVAL_BOOT_MS}"

wifi:
  id: mywifi
#  password: !secret wifi_password

api:
  id: myapi
  encryption:
#    key: !secret api_key

packages:
  - !include src/pkg_board.yaml
  - !include src/pkg_network.yaml
  - !include src/pkg_dev_purifier.yaml
  - !include src/pkg_dev_system.yaml
  - !include src/pkg_dev_ui.yaml
  - !include src/pkg_dev_sensor.yaml
  - qr_code:


logger:
  level: INFO
  tx_buffer_size: 160
#  baud_rate: 0
#  logs:
#    # main: DEBUG
#    wifi: NONE
#    esp-idf: NONE

preferences:
  # TODO: consider increasing further after we're done with development
  flash_write_interval: 1min
