substitutions:
  device_name: "box2-0003"
  device_setup_ssid: "box2-0003"
  device_setup_password: "12345678"
  # depending on the display version, we may want to override that
  UI_DISPLAY_TYPE: "SH1106 128x64"
  #UI_DISPLAY_TYPE: "SSD1305 128x64"
  #UI_DISPLAY_TYPE: "SSD1306 128x64"

esphome:
  name: ${device_name}
  friendly_name: ${device_name}
  min_version: 2025.5.0
  name_add_mac_suffix: false

  project:
    name: thecrbox.thebox2
    version: "1.4.0"

  platformio_options:
    build_flags:
      - "-DUSE_DISPLAY_QR_CODE"

  includes:
    - src/purifier_pid.h

external_components:
  - source:
      type: local
      path: src/components

packages:
  - !include src/board.yaml
  - !include src/network.yaml
  - !include src/purifier.yaml
  - !include src/ui_common.yaml
  - !include src/ui_display_and_encoder.yaml

  # for now only one RGB mo at a time is supported, choose:
  #- !include thebox2/ui_rgb_fans.yaml
  - !include src/ui_rgb_strips.yaml

  # for now only one environmental sensor at a time is supported, choose:
  #- !include thebox/sensor_pmsx0003.yaml
  #- !include thebox/sensor_fake.yaml
  - !include src/sensor_sen5x.yaml



logger:
  level: INFO
  baud_rate: 115200
  logs:
    # main: DEBUG
    wifi: NONE
    esp-idf: NONE

preferences:
  # TODO: consider increasing further after we're done with development
  flash_write_interval: 1min
