substitutions:
  WARMUP_DURATION_S: '10'

esphome:
  devices:
    - id: device_purifier
      name: "Purifier"

web_server:
  sorting_groups:
    - id: sorting_group_purifier
      name: "Purifier"
      sorting_weight: 10

    - id: sorting_group_purifier_config_auto
      name: "Config Purifier AUTO"
      sorting_weight: 24
    - id: sorting_group_purifier_config_manual
      name: "Config Purifier MANUAL"
      sorting_weight: 23

    - id: sorting_group_purifier_config_auto_advanced
      name: "Config Purifier AUTO (advanced)"
      sorting_weight: 50

    - id: sorting_group_purifier_diagnostic
      name: "Diagnostic Purifier"
      sorting_weight: 97

packages:
  locked_cfg_boost_proportional_jump: !include { file: thebox_guarded_number.yaml, vars: {
    name: "AUTO: Coef proportional",
    id: cfg_boost_proportional_jump,
    unlocker: unlock_purifier_config_auto_advanced,
    min: 0.1, max: 1.0, step: 0.05, initial: "0.3f",
    group: sorting_group_purifier_config_auto_advanced, weight: 10, device_id: device_purifier } }
  locked_cfg_boost_derivative_jump: !include { file: thebox_guarded_number.yaml, vars: {
    name: "AUTO: Coef derivative",
    id: cfg_boost_derivative_jump,
    unlocker: unlock_purifier_config_auto_advanced,
    min: 0.1, max: 1.0, step: 0.05, initial: "0.3f",
    group: sorting_group_purifier_config_auto_advanced, weight: 11, device_id: device_purifier } }
  locked_cfg_boost_integral_jump: !include { file: thebox_guarded_number.yaml, vars: {
    name: "AUTO: Coef integral",
    id: cfg_boost_integral_jump,
    unlocker: unlock_purifier_config_auto_advanced,
    min: 0.001, max: 0.01, step: 0.0005, initial: "0.002f",
    group: sorting_group_purifier_config_auto_advanced, weight: 12, device_id: device_purifier } }
  locked_cfg_boost_derivative_decay: !include { file: thebox_guarded_number.yaml, vars: {
    name: "AUTO: Decay derivative %/s",
    id: cfg_boost_derivative_decay,
    unlocker: unlock_purifier_config_auto_advanced,
    min: 0.100, max: 0.500, step: 0.01, initial: "0.50f",
    group: sorting_group_purifier_config_auto_advanced, weight: 13, device_id: device_purifier } }
  locked_cfg_boost_integral_decay: !include { file: thebox_guarded_number.yaml, vars: {
    name: "AUTO: Decay integral %/s",
    id: cfg_boost_integral_decay,
    unlocker: unlock_purifier_config_auto_advanced,
    min: 0.000, max: 0.050, step: 0.001, initial: "0.015f",
    group: sorting_group_purifier_config_auto_advanced, weight: 14, device_id: device_purifier } }
  locked_cfg_aqi_deadband: !include { file: thebox_guarded_number.yaml, vars: {
    name: "AUTO: AQI deadband",
    id: cfg_aqi_deadband,
    unlocker: unlock_purifier_config_auto_advanced,
    min: 0.0, max: 50.0, step: 1, initial: "5",
    group: sorting_group_purifier_config_auto_advanced, weight: 15, device_id: device_purifier } }
