substitutions:
  SENSOR_UART_TX: GPIO4
  SENSOR_UART_RX: GPIO15

  SENSOR_SENSIRON_BUS_ID: bus_b

  UI_ENCODER_SW: GPIO34
  UI_ENCODER_A: GPIO36
  UI_ENCODER_B: GPIO39

  UI_DISPLAY_PLATFORM: "ssd1306_i2c"
  #UI_DISPLAY_PLATFORM: "sh1306_dump"
  # big with encoder
  #UI_DISPLAY_TYPE: "SH1106 128x64"
  # small in box
  #UI_DISPLAY_TYPE: "SSD1305 128x64"
  # small black ones
  UI_DISPLAY_TYPE: "SSD1306 128x64"

  UI_DISPLAY_I2C_SDA: GPIO19
  UI_DISPLAY_I2C_SCL: GPIO18

i2c:
  - id: bus_b
    sda: GPIO12
    scl: GPIO13
    scan: false

status_led:
  id: status_indicator_led
  pin:
    number: GPIO23
    inverted: true

button:
  - platform: factory_reset
    id: factory_reset_btn
    name: "Factory Reset"

esp32:
  board: esp32dev
  framework:
    type: esp-idf




