substitutions:
  SENSOR_UART_TX: GPIO15
  SENSOR_UART_RX: GPIO4
  SENSOR_UART_ENABLE: GPIO5

  SENSOR_SENSIRON_BUS_ID: bus_b

  UI_ENCODER_SW: GPIO34
  UI_ENCODER_A: GPIO36
  UI_ENCODER_B: GPIO39

  #UI_DISPLAY_PLATFORM: "ssd1306_i2c"
  UI_DISPLAY_PLATFORM: "sh1306_dump"
  # big with encoder
  #UI_DISPLAY_TYPE: "SH1106 128x64"
  # small in box
  #UI_DISPLAY_TYPE: "SSD1305 128x64"
  # small black ones
  UI_DISPLAY_TYPE: "SSD1306 128x64"

  UI_DISPLAY_I2C_SDA: GPIO19
  UI_DISPLAY_I2C_SCL: GPIO18

i2c:
  - id: bus_b
    sda: GPIO12
    scl: GPIO13
    scan: false

status_led:
  id: status_indicator_led
  pin:
    number: GPIO23
    inverted: false

packages:
  guarded_factory_reset: !include {
    file: thebox_guarded_button.yaml,
    vars: {
      name: "Factory Reset",
      id: factory_reset_btn,
      unlocker: unlock_system_advanced,
      target_button_id: factory_reset_action,
      icon: "mdi:delete-restore",
      group: sorting_group_system,
      weight: 101,
      device_id: device_system,
    }
  }
  guarded_device_restart: !include {
    file: thebox_guarded_button.yaml,
    vars: {
      name: "Device Restart",
      id: device_restart_btn,
      unlocker: unlock_system_advanced,
      target_button_id: device_restart_action,
      icon: "mdi:restart",
      group: sorting_group_system,
      weight: 102,
      device_id: device_system,
    }
  }

button:
  # Internal buttons that perform the actual actions
  - platform: factory_reset
    id: factory_reset_action
    name: "Factory Reset Action"
    internal: true
  - platform: restart
    id: device_restart_action
    name: "Device Restart Action"
    internal: true


esp32:
  board: esp32dev
  framework:
    type: esp-idf




