uart:
  tx_pin: ${SENSOR_UART_TX}
  rx_pin: ${SENSOR_UART_RX}
  baud_rate: 9600

switch:
  - platform: gpio
    pin: ${SENSOR_UART_ENABLE}
    name: "pmsx003 SET pin"
    restore_mode: RESTORE_DEFAULT_ON
    internal: false

sensor:
  - platform: pmsx003
    type: PMSX003
    update_interval: ${SENSOR_UPDATE_INTERVAL}
    pm_1_0:
      name: "${SENSOR_NAME_PM_1_0} (PMSX003)"
      id: sensor_pm_1_0_pms
      device_id: device_sensor
      internal: true
      accuracy_decimals: 1
      web_server:
        sorting_group_id: sorting_group_sensor
      filters:
        - throttle_average: 10s
        - heartbeat: 10s
        - filter_out: nan
        - skip_initial: 3
      on_raw_value:
        then:
          - lambda: |-
              id(sensor_pm_1_0_in).publish_state(x);
              id(pm_sensor_active_source) = 3;
          - script.execute: update_pm_data_outputs
          - script.execute: update_air_quality_outputs
    pm_2_5:
      name: "${SENSOR_NAME_PM_2_5} (PMSX003)"
      id: sensor_pm_2_5_pms
      device_id: device_sensor
      internal: true
      accuracy_decimals: 1
      web_server:
        sorting_group_id: sorting_group_sensor
      filters:
        - throttle_average: 10s
        - heartbeat: 10s
        - filter_out: nan
        - skip_initial: 3
      on_raw_value:
        then:
          - lambda: |-
              id(sensor_pm_2_5_in).publish_state(x);
              id(pm_sensor_active_source) = 3;
          - script.execute: update_pm_data_outputs
          - script.execute: update_air_quality_outputs
    pm_10_0:
      name: "${SENSOR_NAME_PM_10_0} (PMSX003)"
      id: sensor_pm_10_0_pms
      device_id: device_sensor
      internal: true
      accuracy_decimals: 1
      web_server:
        sorting_group_id: sorting_group_sensor
      filters:
        - throttle_average: 10s
        - heartbeat: 10s
        - filter_out: nan
        - skip_initial: 3
      on_raw_value:
        then:
          - lambda: |-
              id(sensor_pm_10_0_in).publish_state(x);
              id(pm_sensor_active_source) = 3;
          - script.execute: update_pm_data_outputs
          - script.execute: update_air_quality_outputs
