esphome:
  devices:
    - id: device_system
      name: "System"

web_server:
  sorting_groups:
    - id: sorting_group_system
      name: "System"
      sorting_weight: 98

switch:
  - platform: template
    id: unlock_system_advanced
    name: "Unlock advanced settings (15s)"
    icon: "mdi:lock"
    optimistic: true
    restore_mode: always_off
    device_id: device_system
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: 1
    turn_on_action:
#      - lambda: |-
#          id(myota).set_auth_password("new password");
      - delay: 15s
      - switch.turn_off: unlock_system_advanced

packages:
  guarded_factory_reset: !include {
    file: thebox_guarded_button.yaml,
    vars: {
      name: "Factory Reset",
      id: factory_reset_btn,
      unlocker: unlock_system_advanced,
      target_button_id: factory_reset_action,
      icon: "mdi:delete-restore",
      group: sorting_group_system,
      weight: 101,
      device_id: device_system,
    }
  }
  guarded_device_restart: !include {
    file: thebox_guarded_button.yaml,
    vars: {
      name: "Device Restart",
      id: device_restart_btn,
      unlocker: unlock_system_advanced,
      target_button_id: device_restart_action,
      icon: "mdi:restart",
      group: sorting_group_system,
      weight: 102,
      device_id: device_system,
    }
  }

button:
  # Internal buttons that perform the actual actions
  - platform: factory_reset
    id: factory_reset_action
    name: "Factory Reset Action"
    internal: true
  - platform: restart
    id: device_restart_action
    name: "Device Restart Action"
    internal: true
